### ISSUE TITLE
The specified alg value is not allowed

### ISSUE THREAD

**Issue by micromachine** [oleg-agapov/flask-jwt-auth#4]
Iv'e tired to run this example but without success. 

```
[2020-01-08 08:28:14,067] ERROR in app: Exception on /secret [GET]
Traceback (most recent call last):
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper
    verify_jwt_in_request()
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 294, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask_jwt_extended/utils.py", line 118, in decode_token
    allow_expired=allow_expired
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/flask_jwt_extended/tokens.py", line 140, in decode_jwt
    leeway=leeway, options=options, issuer=issuer)
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/jwt/api_jwt.py", line 92, in decode
    jwt, key=key, algorithms=algorithms, options=options, **kwargs
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/jwt/api_jws.py", line 156, in decode
    key, algorithms)
  File "/home/devuser/private/projects/venv/lib/python3.6/site-packages/jwt/api_jws.py", line 216, in _verify_signature
    raise InvalidAlgorithmError('The specified alg value is not allowed')
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed
127.0.0.1 - - [08/Jan/2020 08:28:14] "GET /secret HTTP/1.1" 500 -
```

**Comment by oleg-agapov** [comment]
@micromachine could you show your code?

**Comment by micromachine** [comment]
It's cloned from your repository ...  I didn't make any changes
